spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 880611Gakki.
    url: jdbc:mysql://39.97.186.233/miaosha?characterEncoding=utf-8&usingSSL=false&zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 39.97.186.233
    port: 6379
    database: 1
    jedis:
      pool:
        max-active: 50
        min-idle: 20
    password: 123456

mq:
  nameserver:
    addr: 39.97.186.233:9876
  topicname: stock

tx:
  sms:
    secretId: AKIDw1umT32G2rQrR09mhT3UmqKcnoiOaCP8
    secretKey: MODEMNBHm6FDJhrpi2EIDVEh4En7C6xL
    appId: 1400490611
    templateId: 880029
    smsSign: 沉沦的白非立公众号